---
title: "Data Sources"
output:
  html_document:
    df_print: paged
---
# Data Sources

## Public Health Scotland

### Screening

#### Scottish Bowel Screening Programme
[Scottish bowel screening programme statistics For the period of invitations from May 2020 to April 2022](https://publichealthscotland.scot/publications/scottish-bowel-screening-programme-statistics/scottish-bowel-screening-programme-statistics-for-the-period-of-invitations-from-may-2020-to-april-2022/)

Data: [2023-02-21-bowel-screening-kpi-report.xlsx](https://publichealthscotland.scot/media/17689/2023-02-21-bowel-screening-kpi-report.xlsx)

Key Performance Indicators Report: Nov 2022 data submission
Invitations between 1st May 2020 and 30th April 2022

"Men and women registered with a Community Health Index number aged between 50-74 years who are invited to participate..."

"Data are submitted to Public Health Scotland by BoSS (the bowel screening IT system) and by NHS boards twice per year in May and November. "

"All data are presented by NHS board and sex. "

"This report contains the Key Performance Indicators for the Nov 2022 data submission"

"All colorectal cancers and adenomas in this report were detected through the screening programme."

"Any reference to colorectal cancer includes polyp cancers but excludes non-invasive lesions."

"IMPORTANT: The small numbers of positive test results recorded for NHS Orkney, NHS Western Isles and NHS Shetland (due to their small population sizes) require that caution "

"Uptake (KPI 1)
Uptake is defined as the proportion of invites which are returned as a correctly
completed kit (i.e. a positive or negative test result). It is a key measure of the
acceptability of the test to the public."
Data: Sheet: KPI_1




*Definitions	*				
Adenoma		a benign epithelial tumour			
Colorectal cancer		Also referred to as bowel cancer. For the purposes of this publication bowel/colorectal cancer refers to colorectal cancers			
		 (including polyp cancers, but excluding non-invasive lesions).			
Colonoscopy		endoscopic examination of the colon			
Dukes' stage		a system devised by Cuthbert Dukes that describes the spread of the tumour and forms the main component in identifying the ‘stage’ of bowel cancer			
FIT test		Faecal Immunochemical Test			
FOBT		Faecal Occult Blood Test			
Histology		the study of cells and tissue at a microscopic level			
Polyp		a cluster of cells which project as a growth, usually on a stalk, from the mucosal lining of the bowel			
PPV		Positive Predictive Value - the proportion of those who have a positive test who actually have disease			
SIMD		Scottish Index of Multiple Deprivation			

## Death

### All causes of death and selected causes

# Table 1: All ages age-standardised death rates for all causes and certain selected causes, Scotland, 1994 to 2022
# https://www.nrscotland.gov.uk/files//statistics/age-standardised-death-rates-esp/2022/age-standard-death-rates-22-tab1.zip
# Table file: age-standard-death-rates-22-data-for-chart.csv

# Background:
# https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/vital-events/deaths/age-standardised-death-rates-calculated-using-the-esp
