---
title: "Cancer in Scotland"
author: "Lesley Duff"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
---
---
```{r setup_report, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  error = FALSE,
  message = FALSE
)
```
# Cancer in Scotland

```{r}
library(readr)
```

```{r}
source(here::here("R/phs_data_info.R"))
source(here::here("R/screening.R"))
# Retrieve helper functions for manipulating bowel cancer screening data
source(here::here("R/theming.R"))

screening_bowel_cancer_takeup_all <- read_csv(here::here(
  "data_clean", phs_screening_bowel_uptake_filepath
))
```
```{r}
# Set custom theme
theme_set(theme_cancer_in_scotland())
```
# Overview

## Data Quality
https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/vital-events/deaths/deaths-background-information/quality-of-nrs-data-on-deaths

```{r, child=c('../analysis/analysis_death.Rmd')}
```

```{r, child=c('../analysis/analysis_incidence.Rmd')}
```

```{r, child=c('../analysis/analysis_screening.Rmd')}
```

```{r, child=c('../analysis/analysis_waiting_times.Rmd')}
```

## Assumptions
* NRS use "." in some columns - I'm assuming they just mean not available. It's
in things like columns for COVID in year 1994 etc. Or changes in what's 
recorded.