---
title: "Project Log"
subtitle: "Cancer in Scotland"
author: "Lesley Duff"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
---
# Project Log: Cancer in Scotland

Log of actions taken during project.

## 2023-10-09 Monday
* Standup
* Discussion with instructors over choice of brief and plan
* Created project log file (this document)
* Data - researching bowel cancer screening data. https://publichealthscotland.scot/publications/scottish-bowel-screening-programme-statistics/scottish-bowel-screening-programme-statistics-for-the-period-of-invitations-from-may-2020-to-april-2022/
  * Created data_sources document to track info around datasets
  * Downloading latest report 
  * Relevant
    * "Overall uptake of screening" KP1,
    * "Overall uptake of screening by deprivation area" KP2, 
    * "Percentage of people with a positive screening test result" KP3 
    * "Percentage of people that had a cancer detected" - percentage of people with colorectal cancer, out of those with a final outright screening test result.
	* Experimented with extracting a range for KP1
	* Wrote cleaning script for KP1
* DETOUR: WAITING FOR BRITISH GAS ADVISOR..."Now 201st in line"
  * Testing shiny demos https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/index.html

## 2023-10-10 Tuesday
* Standup
* Bowel Cancer screening
  * Plots
  * Add to main report
  
* NRS Death data
  * Found better table for causes of death but more processing required
  * Puzzling over why they have split one table in two? Programatically what's
  the best way of handling? Have gone down the road of extracting two tables by
  range then combining.
  * Rows with columns with empty values but the value is in a previous row?
  I'm going to experiment with 'fill' - is this the best way? https://tidyr.tidyverse.org/reference/fill.html
  * Tried contacting Jamie and David (hadn't noticed David not working afternoon)
  * Spoke to Jamie, general catch up, mooted doing decision tree
  * Switching general death dataset to Age-standardised Death Rates Calculated Using the European Standard Population
  https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/vital-events/deaths/age-standardised-death-rates-calculated-using-the-esp. Better because of age standardised, NB rate not numbers and
  nicer breakdown of simpler naming of causes and public-friendly labels.
  
## 2023-10-11 Wednesday
* Standup
* Death:
    * Continuing on NRS death data, comparing Cancer to other non-cancer deaths
    - created a pie chart, ha!
    * Had a bit of a faff removing NAs. NRS have fields with "." in them for
    things like COVID in 1994 - assuming they just mean not available.
* Looking at DT::DataTable options for presenting info in analysis

## 2023-10-12 Thursday
* Standup
* Tidy up plots for death
* Work on restructuring report files to make use of child documents to pull 
separate analysis notebooks into the main report
* Incidence:
  * Starting looking at new cases/incidence of different cancer types.  
[Incidence at Scotland Level](https://www.opendata.nhs.scot/dataset/annual-cancer-incidence/resource/72c852b8-ee28-4fd8-84a9-5f415f4bc325).  
https://www.opendata.nhs.scot/dataset/c2c59eb1-3aff-48d2-9e9c-60ca8605431d/resource/72c852b8-ee28-4fd8-84a9-5f415f4bc325/download/opendata_inc9721_scotland.csv
  * Standardised the cleaning scripts
* Shiny - revisiting looking for a suitable layout

## 2023-10-13 Friday
* Standup
* Consulted with David over Shiny bslib issue == feature needed for multiple 
panels on a page only available in development version. Have installed dev version.
* Chat with David and Al about possible approaches to modelling. Decision Tree 
and Time series forecasting some possible approaches.
* Incidences:
  * With the large tidy dataset (over a million rows), spending time on nailing the queries to return as small a set of data as possible before 
trying plotting
  * Line plot for incidences
* Work on custom ggplot theme

## 2023-10-14 Saturday
* Incidence:
  * Queries for cancer type

## 2023-10-17 Tuesday
* Incidence: 
  * Sorting out the filtering by sex
  * visualisations of cancer by cancer types
  
## 2023-10-17 Tuesday
* Incidence:
  * Shiny document - Interactive Cancer Risk Tool
  https://shiny.posit.co/r/articles/build/interactive-docs/
  
* Screening:
  * Tidy up plots/palettes and more commentary

## 2023-10-19 Thursday
* Work on presentation

## 2023-10-20 Friday
* Presentation

## 2023-11-13 Monday
* Clean up code and structure final analysis report
* Write README files
* Write final PDA report